# Assignment

Import numpy as np

In [1]:
import numpy as np

Make a python list => \[1,2,3,4,5\]

Convert it into numpy array and print it

In [2]:

list1=[1,2,3,4,5]
list_np=np.array(list1)
type(list1)
list_np

array([1, 2, 3, 4, 5])

Make a python matrix (3 x 3) => \[[1,2,3],[4,5,6],[7,8,9]\]

Convert it into numpy array and print it

In [3]:
matrix=[[1,2,3],[4,5,6],[7,8,9]]
matrix_np=np.array(matrix)
type(matrix)
matrix_np

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Make a matrix (3 x 3) using built-in methods (like arange(), reshape() etc.):

\[ [1,3,5],

 [7,9,11],
 
 [13,15,17] \]

In [4]:
a=np.arange(1,19,2)
a.reshape(3,3)

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

Create a numpy array with 10 random numbers from 0 to 10 (there should be few numbers greater than 1)

In [5]:
ra=np.random.randint(0,10,10)
ra

array([2, 0, 3, 8, 8, 9, 3, 6, 7, 4])

Create numpy array => \[1,2,3,4,5\] and convert it to 2D array with 5 rows

In [6]:
list2=[1,2,3,4,5]
list2_np=np.array(list2)
list2_np.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

Print the shape of the above created array

In [7]:
list2_np.shape

(5,)

Create a numpy array with 10 elements in it. Access and print its 3rd, 4th and 9th element.

In [12]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
arr[2]

3

Print alternate elements of that array

In [13]:
arr[3]

4

In [14]:
arr[8]

9

In [15]:
arr[0:9:2]

array([1, 3, 5, 7, 9])

Change last 3 elements into 100 using broadcasting and print

In [16]:
arr[7:]=[100,100,100]
arr

array([  1,   2,   3,   4,   5,   6,   7, 100, 100, 100])

Create a 5 x 5 matrix (fill it with any element you like), print it.

Then print the middle (3 x 3) matrix.

In [18]:
arr1=np.arange(0,25).reshape(5,5)
arr1


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
arr1[1:4,1:4]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])